import {ICurrency} from 'models/ICurrency';

export const DATABASE = {
  FILE_NAME: 'my_finance.db',
  BACKUP_FILE_NAME: 'my_finance_backup.db',
};

export const currenciesISO: ICurrency[] = [
  {
    alphabetic_code: 'AFN',
    currency: 'Afghani',
    country: 'AFGHANISTAN',
    numeric_code: 971,
  },
  {
    alphabetic_code: 'DZD',
    currency: 'Algerian Dinar',
    country: 'ALGERIA',
    numeric_code: 12,
  },
  {
    alphabetic_code: 'AOA',
    currency: 'Kwanza',
    country: 'ANGOLA',
    numeric_code: 973,
  },
  {
    alphabetic_code: 'XCD',
    currency: 'East Caribbean Dollar',
    country: 'ANGUILLA',
    numeric_code: 951,
  },

  {
    alphabetic_code: 'XCD',
    currency: 'East Caribbean Dollar',
    country: 'ANTIGUA AND BARBUDA',
    numeric_code: 951,
  },
  {
    alphabetic_code: 'ARS',
    currency: 'Argentine Peso',
    country: 'ARGENTINA',
    numeric_code: 32,
  },
  {
    alphabetic_code: 'AMD',
    currency: 'Armenian Dram',
    country: 'ARMENIA',
    numeric_code: 51,
  },
  {
    alphabetic_code: 'AWG',
    currency: 'Aruban Florin',
    country: 'ARUBA',
    numeric_code: 533,
  },
  {
    alphabetic_code: 'AUD',
    currency: 'Australian Dollar',
    country: 'AUSTRALIA',
    numeric_code: 36,
  },
  {
    alphabetic_code: 'AZN',
    currency: 'Azerbaijan Manat',
    country: 'AZERBAIJAN',
    numeric_code: 944,
  },
  {
    alphabetic_code: 'BSD',
    currency: 'Bahamian Dollar',
    country: 'BAHAMAS (THE)',
    numeric_code: 44,
  },
  {
    alphabetic_code: 'BHD',
    currency: 'Bahraini Dinar',
    country: 'BAHRAIN',

    numeric_code: 48,
  },
  {
    alphabetic_code: 'BDT',
    currency: 'Taka',
    country: 'BANGLADESH',
    numeric_code: 50,
  },
  {
    alphabetic_code: 'BBD',
    currency: 'Barbados Dollar',
    country: 'BARBADOS',
    numeric_code: 52,
  },
  {
    alphabetic_code: 'BYN',
    currency: 'Belarusian Ruble',
    country: 'BELARUS',
    numeric_code: 933,
  },
  {
    alphabetic_code: 'BZD',
    currency: 'Belize Dollar',
    country: 'BELIZE',
    numeric_code: 84,
  },
  {
    alphabetic_code: 'XOF',
    currency: 'CFA Franc BCEAO',
    country: 'BENIN',

    numeric_code: 952,
  },
  {
    alphabetic_code: 'BMD',
    currency: 'Bermudian Dollar',
    country: 'BERMUDA',
    numeric_code: 60,
  },
  {
    alphabetic_code: 'INR',
    currency: 'Indian Rupee',
    country: 'BHUTAN',
    numeric_code: 356,
  },
  {
    alphabetic_code: 'BTN',
    currency: 'Ngultrum',
    country: 'BHUTAN',
    numeric_code: 64,
  },
  {
    alphabetic_code: 'BOB',
    currency: 'Boliviano',
    country: 'BOLIVIA (PLURINATIONAL STATE OF)',
    numeric_code: 68,
  },
  {
    alphabetic_code: 'BOV',
    currency: 'Mvdol',
    country: 'BOLIVIA (PLURINATIONAL STATE OF)',
    numeric_code: 984,
  },
  {
    alphabetic_code: 'BAM',
    currency: 'Convertible Mark',
    country: 'BOSNIA AND HERZEGOVINA',
    numeric_code: 977,
  },
  {
    alphabetic_code: 'BWP',
    currency: 'Pula',
    country: 'BOTSWANA',
    numeric_code: 72,
  },
  {
    alphabetic_code: 'NOK',
    currency: 'Norwegian Krone',
    country: 'BOUVET ISLAND',
    numeric_code: 578,
  },
  {
    alphabetic_code: 'BRL',
    currency: 'Brazilian Real',
    country: 'BRAZIL',
    numeric_code: 986,
  },
  {
    alphabetic_code: 'BND',
    currency: 'Brunei Dollar',
    country: 'BRUNEI DARUSSALAM',
    numeric_code: 96,
  },
  {
    alphabetic_code: 'XOF',
    currency: 'CFA Franc BCEAO',
    country: 'BURKINA FASO',

    numeric_code: 952,
  },
  {
    alphabetic_code: 'BIF',
    currency: 'Burundi Franc',
    country: 'BURUNDI',
    numeric_code: 108,
  },
  {
    alphabetic_code: 'CVE',
    currency: 'Cabo Verde Escudo',
    country: 'CABO VERDE',
    numeric_code: 132,
  },
  {
    alphabetic_code: 'KHR',
    currency: 'Riel',
    country: 'CAMBODIA',
    numeric_code: 116,
  },
  {
    alphabetic_code: 'XAF',
    currency: 'CFA Franc BEAC',
    country: 'CAMEROON',
    numeric_code: 950,
  },
  {
    alphabetic_code: 'CAD',
    currency: 'Canadian Dollar',
    country: 'CANADA',
    numeric_code: 124,
  },
  {
    alphabetic_code: 'KYD',
    currency: 'Cayman Islands Dollar',
    country: 'CAYMAN ISLANDS (THE)',
    numeric_code: 136,
  },
  {
    alphabetic_code: 'XAF',
    currency: 'CFA Franc BEAC',
    country: 'CENTRAL AFRICAN REPUBLIC (THE)',
    numeric_code: 950,
  },
  {
    alphabetic_code: 'XAF',
    currency: 'CFA Franc BEAC',
    country: 'CHAD',
    numeric_code: 950,
  },
  {
    alphabetic_code: 'CLP',
    currency: 'Chilean Peso',
    country: 'CHILE',
    numeric_code: 152,
  },
  {
    alphabetic_code: 'CNY',
    currency: 'Yuan Renminbi',
    country: 'CHINA',
    numeric_code: 156,
  },
  {
    alphabetic_code: 'AUD',
    currency: 'Australian Dollar',
    country: 'CHRISTMAS ISLAND',
    numeric_code: 36,
  },
  {
    alphabetic_code: 'COP',
    currency: 'Colombian Peso',
    country: 'COLOMBIA',
    numeric_code: 170,
  },
  {
    alphabetic_code: 'KMF',
    currency: 'Comorian Franc',
    country: 'COMOROS (THE)',
    numeric_code: 174,
  },
  {
    alphabetic_code: 'CDF',
    currency: 'Congolese Franc',
    country: 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
    numeric_code: 976,
  },
  {
    alphabetic_code: 'XAF',
    currency: 'CFA Franc BEAC',
    country: 'CONGO (THE)',
    numeric_code: 950,
  },
  {
    alphabetic_code: 'NZD',
    currency: 'New Zealand Dollar',
    country: 'COOK ISLANDS (THE)',
    numeric_code: 554,
  },
  {
    alphabetic_code: 'CRC',
    currency: 'Costa Rican Colon',
    country: 'COSTA RICA',
    numeric_code: 188,
  },
  {
    alphabetic_code: 'XOF',
    currency: 'CFA Franc BCEAO',
    country: 'COTE DIVOIRE',
    numeric_code: 952,
  },
  {
    alphabetic_code: 'HRK',
    currency: 'Kuna',
    country: 'CROATIA',
    numeric_code: 191,
  },
  {
    alphabetic_code: 'CUP',
    currency: 'Cuban Peso',
    country: 'CUBA',
    numeric_code: 192,
  },
  {
    alphabetic_code: 'CUC',
    currency: 'Peso Convertible',
    country: 'CUBA',
    numeric_code: 931,
  },
  {
    alphabetic_code: 'DJF',
    currency: 'Djibouti Franc',
    country: 'DJIBOUTI',

    numeric_code: 262,
  },
  {
    alphabetic_code: 'XCD',
    currency: 'East Caribbean Dollar',
    country: 'DOMINICA',
    numeric_code: 951,
  },
  {
    alphabetic_code: 'DOP',
    currency: 'Dominican Peso',
    country: 'DOMINICAN REPUBLIC (THE)',
    numeric_code: 214,
  },
  {
    alphabetic_code: 'EGP',
    currency: 'Egyptian Pound',
    country: 'EGYPT',
    numeric_code: 818,
  },
  {
    alphabetic_code: 'SVC',
    currency: 'El Salvador Colon',
    country: 'EL SALVADOR',
    numeric_code: 222,
  },

  {
    alphabetic_code: 'XAF',
    currency: 'CFA Franc BEAC',
    country: 'EQUATORIAL GUINEA',

    numeric_code: 950,
  },
  {
    alphabetic_code: 'ERN',
    currency: 'Nakfa',
    country: 'ERITREA',
    numeric_code: 232,
  },
  {
    alphabetic_code: 'SZL',
    currency: 'Lilangeni',
    country: 'ESWATINI',
    numeric_code: 748,
  },
  {
    alphabetic_code: 'ETB',
    currency: 'Ethiopian Birr',
    country: 'ETHIOPIA',
    numeric_code: 230,
  },
  {
    alphabetic_code: 'EUR',
    currency: 'Euro',
    country: 'EUROPEAN UNION',
    numeric_code: 978,
  },
  {
    alphabetic_code: 'FKP',
    currency: 'Falkland Islands Pound',
    country: 'FALKLAND ISLANDS (THE) [MALVINAS]',
    numeric_code: 238,
  },
  {
    alphabetic_code: 'DKK',
    currency: 'Danish Krone',
    country: 'FAROE ISLANDS (THE)',
    numeric_code: 208,
  },
  {
    alphabetic_code: 'FJD',
    currency: 'Fiji Dollar',
    country: 'FIJI',
    numeric_code: 242,
  },
  {
    alphabetic_code: 'XPF',
    currency: 'CFP Franc',
    country: 'FRENCH POLYNESIA',
    numeric_code: 953,
  },
  {
    alphabetic_code: 'XAF',
    currency: 'CFA Franc BEAC',
    country: 'GABON',

    numeric_code: 950,
  },
  {
    alphabetic_code: 'GMD',
    currency: 'Dalasi',
    country: 'GAMBIA (THE)',
    numeric_code: 270,
  },
  {
    alphabetic_code: 'GEL',
    currency: 'Lari',
    country: 'GEORGIA',
    numeric_code: 981,
  },
  {
    alphabetic_code: 'GHS',
    currency: 'Ghana Cedi',
    country: 'GHANA',
    numeric_code: 936,
  },
  {
    alphabetic_code: 'GIP',
    currency: 'Gibraltar Pound',
    country: 'GIBRALTAR',
    numeric_code: 292,
  },
  {
    alphabetic_code: 'DKK',
    currency: 'Danish Krone',
    country: 'GREENLAND',
    numeric_code: 208,
  },
  {
    alphabetic_code: 'XCD',
    currency: 'East Caribbean Dollar',
    country: 'GRENADA',
    numeric_code: 951,
  },
  {
    alphabetic_code: 'GTQ',
    currency: 'Quetzal',
    country: 'GUATEMALA',
    numeric_code: 320,
  },
  {
    alphabetic_code: 'GNF',
    currency: 'Guinean Franc',
    country: 'GUINEA',

    numeric_code: 324,
  },
  {
    alphabetic_code: 'XOF',
    currency: 'CFA Franc BCEAO',
    country: 'GUINEA-BISSAU',

    numeric_code: 952,
  },
  {
    alphabetic_code: 'GYD',
    currency: 'Guyana Dollar',
    country: 'GUYANA',
    numeric_code: 328,
  },
  {
    alphabetic_code: 'HTG',
    currency: 'Gourde',
    country: 'HAITI',
    numeric_code: 332,
  },
  {
    alphabetic_code: 'AUD',
    currency: 'Australian Dollar',
    country: 'HEARD ISLAND AND McDONALD ISLANDS',
    numeric_code: 36,
  },
  {
    alphabetic_code: 'HNL',
    currency: 'Lempira',
    country: 'HONDURAS',
    numeric_code: 340,
  },
  {
    alphabetic_code: 'HKD',
    currency: 'Hong Kong Dollar',
    country: 'HONG KONG',
    numeric_code: 344,
  },
  {
    alphabetic_code: 'HUF',
    currency: 'Forint',
    country: 'HUNGARY',
    numeric_code: 348,
  },
  {
    alphabetic_code: 'ISK',
    currency: 'Iceland Krona',
    country: 'ICELAND',

    numeric_code: 352,
  },
  {
    alphabetic_code: 'INR',
    currency: 'Indian Rupee',
    country: 'INDIA',
    numeric_code: 356,
  },
  {
    alphabetic_code: 'IDR',
    currency: 'Rupiah',
    country: 'INDONESIA',
    numeric_code: 360,
  },
  {
    alphabetic_code: 'XDR',
    currency: 'SDR (Special Drawing Right)',
    country: 'INTERNATIONAL MONETARY FUND (IMF)',

    numeric_code: 960,
  },
  {
    alphabetic_code: 'IRR',
    currency: 'Iranian Rial',
    country: 'IRAN (ISLAMIC REPUBLIC OF)',
    numeric_code: 364,
  },
  {
    alphabetic_code: 'IQD',
    currency: 'Iraqi Dinar',
    country: 'IRAQ',

    numeric_code: 368,
  },
  {
    alphabetic_code: 'ILS',
    currency: 'New Israeli Sheqel',
    country: 'ISRAEL',
    numeric_code: 376,
  },
  {
    alphabetic_code: 'JMD',
    currency: 'Jamaican Dollar',
    country: 'JAMAICA',
    numeric_code: 388,
  },
  {
    alphabetic_code: 'JPY',
    currency: 'Yen',
    country: 'JAPAN',

    numeric_code: 392,
  },
  {
    alphabetic_code: 'JOD',
    currency: 'Jordanian Dinar',
    country: 'JORDAN',

    numeric_code: 400,
  },
  {
    alphabetic_code: 'KZT',
    currency: 'Tenge',
    country: 'KAZAKHSTAN',
    numeric_code: 398,
  },
  {
    alphabetic_code: 'KES',
    currency: 'Kenyan Shilling',
    country: 'KENYA',
    numeric_code: 404,
  },
  {
    alphabetic_code: 'AUD',
    currency: 'Australian Dollar',
    country: 'KIRIBATI',
    numeric_code: 36,
  },
  {
    alphabetic_code: 'KPW',
    currency: 'North Korean Won',
    country: 'KOREA (THE DEMOCRATIC PEOPLE"S REPUBLIC OF)',
    numeric_code: 408,
  },
  {
    alphabetic_code: 'KRW',
    currency: 'Won',
    country: 'KOREA (THE REPUBLIC OF)',

    numeric_code: 410,
  },
  {
    alphabetic_code: 'KWD',
    currency: 'Kuwaiti Dinar',
    country: 'KUWAIT',

    numeric_code: 414,
  },
  {
    alphabetic_code: 'KGS',
    currency: 'Som',
    country: 'KYRGYZSTAN',
    numeric_code: 417,
  },
  {
    alphabetic_code: 'LAK',
    currency: 'Lao Kip',
    country: 'LAO PEOPLE"S DEMOCRATIC REPUBLIC (THE)',
    numeric_code: 418,
  },
  {
    alphabetic_code: 'LBP',
    currency: 'Lebanese Pound',
    country: 'LEBANON',
    numeric_code: 422,
  },
  {
    alphabetic_code: 'LSL',
    currency: 'Loti',
    country: 'LESOTHO',
    numeric_code: 426,
  },
  {
    alphabetic_code: 'ZAR',
    currency: 'Rand',
    country: 'LESOTHO',
    numeric_code: 710,
  },
  {
    alphabetic_code: 'LRD',
    currency: 'Liberian Dollar',
    country: 'LIBERIA',
    numeric_code: 430,
  },
  {
    alphabetic_code: 'LYD',
    currency: 'Libyan Dinar',
    country: 'LIBYA',

    numeric_code: 434,
  },
  {
    alphabetic_code: 'CHF',
    currency: 'Swiss Franc',
    country: 'LIECHTENSTEIN',
    numeric_code: 756,
  },
  {
    alphabetic_code: 'MOP',
    currency: 'Pataca',
    country: 'MACAO',
    numeric_code: 446,
  },
  {
    alphabetic_code: 'MKD',
    currency: 'Denar',
    country: 'NORTH MACEDONIA',
    numeric_code: 807,
  },
  {
    alphabetic_code: 'MGA',
    currency: 'Malagasy Ariary',
    country: 'MADAGASCAR',
    numeric_code: 969,
  },
  {
    alphabetic_code: 'MWK',
    currency: 'Malawi Kwacha',
    country: 'MALAWI',
    numeric_code: 454,
  },
  {
    alphabetic_code: 'MYR',
    currency: 'Malaysian Ringgit',
    country: 'MALAYSIA',
    numeric_code: 458,
  },
  {
    alphabetic_code: 'MVR',
    currency: 'Rufiyaa',
    country: 'MALDIVES',
    numeric_code: 462,
  },
  {
    alphabetic_code: 'XOF',
    currency: 'CFA Franc BCEAO',
    country: 'MALI',

    numeric_code: 952,
  },
  {
    alphabetic_code: 'MRU',
    currency: 'Ouguiya',
    country: 'MAURITANIA',
    numeric_code: 929,
  },
  {
    alphabetic_code: 'MUR',
    currency: 'Mauritius Rupee',
    country: 'MAURITIUS',
    numeric_code: 480,
  },
  {
    alphabetic_code: 'XUA',
    currency: 'ADB Unit of Account',
    country: 'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP',

    numeric_code: 965,
  },
  {
    alphabetic_code: 'MXN',
    currency: 'Mexican Peso',
    country: 'MEXICO',
    numeric_code: 484,
  },
  {
    alphabetic_code: 'MXV',
    currency: 'Mexican Unidad de Inversion (UDI)',
    country: 'MEXICO',
    numeric_code: 979,
  },
  {
    alphabetic_code: 'MDL',
    currency: 'Moldovan Leu',
    country: 'MOLDOVA (THE REPUBLIC OF)',
    numeric_code: 498,
  },
  {
    alphabetic_code: 'MNT',
    currency: 'Tugrik',
    country: 'MONGOLIA',
    numeric_code: 496,
  },
  {
    alphabetic_code: 'XCD',
    currency: 'East Caribbean Dollar',
    country: 'MONTSERRAT',
    numeric_code: 951,
  },
  {
    alphabetic_code: 'MAD',
    currency: 'Moroccan Dirham',
    country: 'MOROCCO',
    numeric_code: 504,
  },
  {
    alphabetic_code: 'MZN',
    currency: 'Mozambique Metical',
    country: 'MOZAMBIQUE',
    numeric_code: 943,
  },
  {
    alphabetic_code: 'MMK',
    currency: 'Kyat',
    country: 'MYANMAR',
    numeric_code: 104,
  },
  {
    alphabetic_code: 'NAD',
    currency: 'Namibia Dollar',
    country: 'NAMIBIA',
    numeric_code: 516,
  },
  {
    alphabetic_code: 'ZAR',
    currency: 'Rand',
    country: 'NAMIBIA',
    numeric_code: 710,
  },
  {
    alphabetic_code: 'AUD',
    currency: 'Australian Dollar',
    country: 'NAURU',
    numeric_code: 36,
  },
  {
    alphabetic_code: 'NPR',
    currency: 'Nepalese Rupee',
    country: 'NEPAL',
    numeric_code: 524,
  },
  {
    alphabetic_code: 'XPF',
    currency: 'CFP Franc',
    country: 'NEW CALEDONIA',

    numeric_code: 953,
  },
  {
    alphabetic_code: 'NZD',
    currency: 'New Zealand Dollar',
    country: 'NEW ZEALAND',
    numeric_code: 554,
  },
  {
    alphabetic_code: 'NIO',
    currency: 'Cordoba Oro',
    country: 'NICARAGUA',
    numeric_code: 558,
  },
  {
    alphabetic_code: 'XOF',
    currency: 'CFA Franc BCEAO',
    country: 'NIGER (THE)',

    numeric_code: 952,
  },
  {
    alphabetic_code: 'NGN',
    currency: 'Naira',
    country: 'NIGERIA',
    numeric_code: 566,
  },
  {
    alphabetic_code: 'NZD',
    currency: 'New Zealand Dollar',
    country: 'NIUE',
    numeric_code: 554,
  },
  {
    alphabetic_code: 'AUD',
    currency: 'Australian Dollar',
    country: 'NORFOLK ISLAND',
    numeric_code: 36,
  },
  {
    alphabetic_code: 'NOK',
    currency: 'Norwegian Krone',
    country: 'NORWAY',
    numeric_code: 578,
  },
  {
    alphabetic_code: 'OMR',
    currency: 'Rial Omani',
    country: 'OMAN',

    numeric_code: 512,
  },
  {
    alphabetic_code: 'PKR',
    currency: 'Pakistan Rupee',
    country: 'PAKISTAN',
    numeric_code: 586,
  },
  {
    alphabetic_code: 'PAB',
    currency: 'Balboa',
    country: 'PANAMA',
    numeric_code: 590,
  },
  {
    alphabetic_code: 'PGK',
    currency: 'Kina',
    country: 'PAPUA NEW GUINEA',
    numeric_code: 598,
  },
  {
    alphabetic_code: 'PYG',
    currency: 'Guarani',
    country: 'PARAGUAY',

    numeric_code: 600,
  },
  {
    alphabetic_code: 'PEN',
    currency: 'Sol',
    country: 'PERU',
    numeric_code: 604,
  },
  {
    alphabetic_code: 'PHP',
    currency: 'Philippine Peso',
    country: 'PHILIPPINES (THE)',
    numeric_code: 608,
  },
  {
    alphabetic_code: 'NZD',
    currency: 'New Zealand Dollar',
    country: 'PITCAIRN',
    numeric_code: 554,
  },
  {
    alphabetic_code: 'PLN',
    currency: 'Zloty',
    country: 'POLAND',
    numeric_code: 985,
  },
  {
    alphabetic_code: 'QAR',
    currency: 'Qatari Rial',
    country: 'QATAR',
    numeric_code: 634,
  },
  {
    alphabetic_code: 'RUB',
    currency: 'Russian Ruble',
    country: 'RUSSIAN FEDERATION',
    numeric_code: 643,
  },
  {
    alphabetic_code: 'RWF',
    currency: 'Rwanda Franc',
    country: 'RWANDA',
    numeric_code: 646,
  },
  {
    alphabetic_code: 'SHP',
    currency: 'Saint Helena Pound',
    country: 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
    numeric_code: 654,
  },
  {
    alphabetic_code: 'XCD',
    currency: 'East Caribbean Dollar',
    country: 'SAINT KITTS AND NEVIS',
    numeric_code: 951,
  },
  {
    alphabetic_code: 'XCD',
    currency: 'East Caribbean Dollar',
    country: 'SAINT LUCIA',
    numeric_code: 951,
  },
  {
    alphabetic_code: 'XCD',
    currency: 'East Caribbean Dollar',
    country: 'SAINT VINCENT AND THE GRENADINES',
    numeric_code: 951,
  },
  {
    alphabetic_code: 'WST',
    currency: 'Tala',
    country: 'SAMOA',
    numeric_code: 882,
  },
  {
    alphabetic_code: 'SAR',
    currency: 'Saudi Riyal',
    country: 'SAUDI ARABIA',
    numeric_code: 682,
  },
  {
    alphabetic_code: 'XOF',
    currency: 'CFA Franc BCEAO',
    country: 'SENEGAL',
    numeric_code: 952,
  },
  {
    alphabetic_code: 'SCR',
    currency: 'Seychelles Rupee',
    country: 'SEYCHELLES',
    numeric_code: 690,
  },
  {
    alphabetic_code: 'SLL',
    currency: 'Leone',
    country: 'SIERRA LEONE',
    numeric_code: 694,
  },
  {
    alphabetic_code: 'SGD',
    currency: 'Singapore Dollar',
    country: 'SINGAPORE',
    numeric_code: 702,
  },
  {
    alphabetic_code: 'SBD',
    currency: 'Solomon Islands Dollar',
    country: 'SOLOMON ISLANDS',
    numeric_code: 90,
  },
  {
    alphabetic_code: 'SOS',
    currency: 'Somali Shilling',
    country: 'SOMALIA',
    numeric_code: 706,
  },
  {
    alphabetic_code: 'ZAR',
    currency: 'Rand',
    country: 'SOUTH AFRICA',
    numeric_code: 710,
  },
  {
    alphabetic_code: 'SSP',
    currency: 'South Sudanese Pound',
    country: 'SOUTH SUDAN',
    numeric_code: 728,
  },
  {
    alphabetic_code: 'LKR',
    currency: 'Sri Lanka Rupee',
    country: 'SRI LANKA',
    numeric_code: 144,
  },
  {
    alphabetic_code: 'SDG',
    currency: 'Sudanese Pound',
    country: 'SUDAN (THE)',
    numeric_code: 938,
  },
  {
    alphabetic_code: 'SRD',
    currency: 'Surinam Dollar',
    country: 'SURINAME',
    numeric_code: 968,
  },
  {
    alphabetic_code: 'SYP',
    currency: 'Syrian Pound',
    country: 'SYRIAN ARAB REPUBLIC',
    numeric_code: 760,
  },
  {
    alphabetic_code: 'TWD',
    currency: 'New Taiwan Dollar',
    country: 'TAIWAN (PROVINCE OF CHINA)',
    numeric_code: 901,
  },
  {
    alphabetic_code: 'TJS',
    currency: 'Somoni',
    country: 'TAJIKISTAN',
    numeric_code: 972,
  },
  {
    alphabetic_code: 'TZS',
    currency: 'Tanzanian Shilling',
    country: 'TANZANIA, UNITED REPUBLIC OF',
    numeric_code: 834,
  },
  {
    alphabetic_code: 'THB',
    currency: 'Baht',
    country: 'THAILAND',
    numeric_code: 764,
  },
  {
    alphabetic_code: 'XOF',
    currency: 'CFA Franc BCEAO',
    country: 'TOGO',

    numeric_code: 952,
  },
  {
    alphabetic_code: 'NZD',
    currency: 'New Zealand Dollar',
    country: 'TOKELAU',
    numeric_code: 554,
  },
  {
    alphabetic_code: 'TOP',
    currency: 'Pa"anga',
    country: 'TONGA',
    numeric_code: 776,
  },
  {
    alphabetic_code: 'TTD',
    currency: 'Trinidad and Tobago Dollar',
    country: 'TRINIDAD AND TOBAGO',
    numeric_code: 780,
  },
  {
    alphabetic_code: 'TND',
    currency: 'Tunisian Dinar',
    country: 'TUNISIA',

    numeric_code: 788,
  },
  {
    alphabetic_code: 'TRY',
    currency: 'Turkish Lira',
    country: 'TURKEY',
    numeric_code: 949,
  },
  {
    alphabetic_code: 'TMT',
    currency: 'Turkmenistan New Manat',
    country: 'TURKMENISTAN',
    numeric_code: 934,
  },

  {
    alphabetic_code: 'AUD',
    currency: 'Australian Dollar',
    country: 'TUVALU',
    numeric_code: 36,
  },
  {
    alphabetic_code: 'UGX',
    currency: 'Uganda Shilling',
    country: 'UGANDA',

    numeric_code: 800,
  },
  {
    alphabetic_code: 'UAH',
    currency: 'Hryvnia',
    country: 'UKRAINE',
    numeric_code: 980,
  },
  {
    alphabetic_code: 'AED',
    currency: 'UAE Dirham',
    country: 'UNITED ARAB EMIRATES (THE)',
    numeric_code: 784,
  },
  {
    alphabetic_code: 'GBP',
    currency: 'Pound Sterling',
    country: 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
    numeric_code: 826,
  },
  {
    alphabetic_code: 'USD',
    currency: 'US Dollar',
    country: 'UNITED STATES OF AMERICA (THE)',
    numeric_code: 840,
  },
  {
    alphabetic_code: 'UYW',
    currency: 'Unidad Previsional',
    country: 'URUGUAY',
    numeric_code: 927,
  },
  {
    alphabetic_code: 'UZS',
    currency: 'Uzbekistan Sum',
    country: 'UZBEKISTAN',
    numeric_code: 860,
  },
  {
    alphabetic_code: 'VUV',
    currency: 'Vatu',
    country: 'VANUATU',
    numeric_code: 548,
  },
  {
    alphabetic_code: 'VND',
    currency: 'Dong',
    country: 'VIETNAM',
    numeric_code: 704,
  },
  {
    alphabetic_code: 'MAD',
    currency: 'Moroccan Dirham',
    country: 'WESTERN SAHARA',
    numeric_code: 504,
  },
  {
    alphabetic_code: 'YER',
    currency: 'Yemeni Rial',
    country: 'YEMEN',
    numeric_code: 886,
  },
  {
    alphabetic_code: 'ZWL',
    currency: 'Zimbabwe Dollar',
    country: 'ZIMBABWE',
    numeric_code: 932,
  },
  {
    alphabetic_code: 'AYM',
    currency: 'Azerbaijan Manat',
    country: 'AZERBAIJAN',
    numeric_code: 945,
  },
  {
    alphabetic_code: 'BYR',
    currency: 'Belarusian Ruble',
    country: 'BELARUS',
    numeric_code: 974,
  },
  {
    alphabetic_code: 'BOP',
    currency: 'Peso boliviano',
    country: 'BOLIVIA',
    numeric_code: 68,
  },
  {
    alphabetic_code: 'BUK',
    currency: 'Kyat',
    country: 'BURMA',
    numeric_code: 104,
  },
  {
    alphabetic_code: 'ECV',
    currency: 'Unidad de Valor Constante (UVC)',
    country: 'ECUADOR',
    numeric_code: 983,
  },
  {
    alphabetic_code: 'GQE',
    currency: 'Ekwele',
    country: 'EQUATORIAL GUINEA',
    numeric_code: 226,
  },
  {
    alphabetic_code: 'FRF',
    currency: 'French Franc',
    country: 'FRANCE',
    numeric_code: 250,
  },
  {
    alphabetic_code: 'GEK',
    currency: 'Georgian Coupon',
    country: 'GEORGIA',
    numeric_code: 268,
  },
  {
    alphabetic_code: 'GHP',
    currency: 'Ghana Cedi',
    country: 'GHANA',
    numeric_code: 939,
  },
  {
    alphabetic_code: 'GNS',
    currency: 'Syli',
    country: 'GUINEA',
    numeric_code: 324,
  },
  {
    alphabetic_code: 'GWP',
    currency: 'Guinea-Bissau Peso',
    country: 'GUINEA-BISSAU',
    numeric_code: 624,
  },
  {
    alphabetic_code: 'ILP',
    currency: 'Pound',
    country: 'ISRAEL',
    numeric_code: 376,
  },
  {
    alphabetic_code: 'MGF',
    currency: 'Malagasy Franc',
    country: 'MADAGASCAR',
    numeric_code: 450,
  },
  {
    alphabetic_code: 'MWK',
    currency: 'Kwacha',
    country: 'MALAWI',

    numeric_code: 454,
  },
  {
    alphabetic_code: 'MVQ',
    currency: 'Maldive Rupee',
    country: 'MALDIVES',

    numeric_code: 462,
  },
  {
    alphabetic_code: 'MLF',
    currency: 'Mali Franc',
    country: 'MALI',

    numeric_code: 466,
  },
  {
    alphabetic_code: 'MTL',
    currency: 'Maltese Lira',
    country: 'MALTA',

    numeric_code: 470,
  },
  {
    alphabetic_code: 'MXP',
    currency: 'Mexican Peso',
    country: 'MEXICO',
    numeric_code: 484,
  },
  {
    alphabetic_code: 'MZM',
    currency: 'Mozambique Metical',
    country: 'MOZAMBIQUE',
    numeric_code: 508,
  },
  {
    alphabetic_code: 'NIC',
    currency: 'Cordoba',
    country: 'NICARAGUA',
    numeric_code: 558,
  },
  {
    alphabetic_code: 'PEH',
    currency: 'Sol',
    country: 'PERU',

    numeric_code: 604,
  },
  {
    alphabetic_code: 'ZAL',
    currency: 'Financial Rand',
    country: 'SOUTH AFRICA',
    numeric_code: 991,
  },
  {
    alphabetic_code: 'SDG',
    currency: 'Sudanese Pound',
    country: 'SOUTH SUDAN',
    numeric_code: 938,
  },
  {
    alphabetic_code: 'RHD',
    currency: 'Rhodesian Dollar',
    country: 'SOUTHERN RHODESIA',
    numeric_code: 716,
  },
  {
    alphabetic_code: 'SDP',
    currency: 'Sudanese Pound',
    country: 'SUDAN',
    numeric_code: 736,
  },
  {
    alphabetic_code: 'SRG',
    currency: 'Surinam Guilder',
    country: 'SURINAME',
    numeric_code: 740,
  },
  {
    alphabetic_code: 'SZL',
    currency: 'Lilangeni',
    country: 'SWAZILAND',
    numeric_code: 748,
  },
  {
    alphabetic_code: 'TJR',
    currency: 'Tajik Ruble',
    country: 'TAJIKISTAN',
    numeric_code: 762,
  },
  {
    alphabetic_code: 'TRY',
    currency: 'New Turkish Lira',
    country: 'TURKEY',
    numeric_code: 949,
  },
  {
    alphabetic_code: 'TMM',
    currency: 'Turkmenistan Manat',
    country: 'TURKMENISTAN',
    numeric_code: 795,
  },
  {
    alphabetic_code: 'UGS',
    currency: 'Uganda Shilling',
    country: 'UGANDA',
    numeric_code: 800,
  },
  {
    alphabetic_code: 'UYP',
    currency: 'Uruguayan Peso',
    country: 'URUGUAY',
    numeric_code: 858,
  },
  {
    alphabetic_code: 'VEF',
    currency: 'Bolivar',
    country: 'VENEZUELA (BOLIVARIAN REPUBLIC OF)',
    numeric_code: 937,
  },
  {
    alphabetic_code: 'VNC',
    currency: 'Old Dong',
    country: 'VIETNAM',
    numeric_code: 704,
  },
  {
    alphabetic_code: 'YDD',
    currency: 'Yemeni Dinar',
    country: 'YEMEN, DEMOCRATIC',
    numeric_code: 720,
  },
  {
    alphabetic_code: 'ZRZ',
    currency: 'Zaire',
    country: 'ZAIRE',
    numeric_code: 180,
  },
  {
    alphabetic_code: 'ZMK',
    currency: 'Zambian Kwacha',
    country: 'ZAMBIA',
    numeric_code: 894,
  },
];
